import React, { useEffect, useState } from "react";
import Button from "../atoms/Button";
import { useRouter } from "next/router";
import Layout from "../Layout/Layout";
import Head from "next/head";
import AOS from 'aos'
import { EyeOffIcon, EyeIcon } from "@heroicons/react/solid";
function Regform() {
  const [form, setForm] = useState({
    phone: "",
    password: "",
  });
  const router = useRouter();
  const onChange = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value,
    });
  };
  const [text, setText] = useState(true);
  const [type, SetType] = useState(true);
  const resetSta = () => {
    SetType(!type);
    setText(!text)
  };
  const onSubmit = async (e) => {
    e.preventDefault();
    const url = "http://localhost:8000/api/v1/login/";
    const data = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "include",
      body: JSON.stringify({
        phone: form.phone,
        password: form.password,
      }),
    });

    const id = await data.json();
    console.log(id);
    if (id.detail) {
      alert("Şifrə və ya nömrə səhvdir..");
    } else {
      const name = id.user_details.name;
      const surname = id.user_details.surname;
      const number= id.user_details.customer_uuids[0]
      localStorage.setItem("name", name);
      localStorage.setItem("surname", surname);
      localStorage.setItem('number',number)
      localStorage.setItem("id", id.access);
      router.push("/");
    }
  };
  useEffect(()=>{
    AOS.init({
      duration : 1000
    });
  })

  const style = "bg-[#131939] px-8 py-2 text-white  ";
  return (
    <Layout>
      <Head>
        <title> Gamboo || Login</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
      </Head>
      <div  className=" w-full h-auto flex justify-center items-center ">
        <form
        data-aos={"fade-right"} 
          onSubmit={(e) => onSubmit(e)}
          className="flex flex-col justify-center  w-full h-[62.5vh] "
        >
          <div className=" flex justify-center ">
            <div className=" flex justify-center w-full">
              <input
                type="text"
                required
                className=" w-[20%] border-b-2 focus:outline-none  rounded-sm  h-11 border-[#131939] indent-4"
                onChange={(e) => onChange(e)}
                value={form.phone}
                placeholder={"Nömrə.."}
                name={"phone"}
                list="number"
              />
              <datalist id="number">
                <option>+99450</option>
                <option>+99455</option>
                <option>+99451</option>
                <option>+99477</option>
                <option>+99460</option>
                <option>+99410</option>
                <option>+99470</option>
                <option>+99499</option>
              </datalist>
            </div>
          </div>
          <div className=" flex mt-8 justify-center w-full">
            <input
              required
              className=" w-[20%] ml-4 border-b-2 focus:outline-none  rounded-sm  h-11 border-[#131939] indent-4"
              onChange={(e) => onChange(e)}
              value={form.password}
              placeholder={"Şifrə.."}
              name={"password"}
              type={type ? 'password' : 'text'  }
            />
           {text ? (
            <EyeOffIcon
              className="w-4 relative right-4 cursor-pointer"
              onClick={resetSta}
            />
          ) : (
            <EyeIcon
              className="w-4 relative right-4 cursor-pointer"
              onClick={resetSta}
            />
          )}
          </div>
          <div className=" flex justify-center mt-8">
            <Button styles={style} name="Daxil ol" />
          </div>
        </form>
      </div>
    </Layout>
  );
}

export default React.memo(Regform);
