import Head from "next/head";
import React from "react";
import Regform from "../atoms/Regform";
import Layout from "../Layout/Layout";

function Register() {
  return (
    <Layout>
      <Head>
        <title> Gamboo || Register </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/favicon.png" sizes="32x32" /> 
      </Head>
      <Regform />
    </Layout>
  );
}

export default React.memo(Register);
